[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["mouwrice <mauricevanwassenhove@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
qtm-rt = "3.0.1"
numpy = "1.26.3"
pygame = "2.5.2"
mediapipe = "0.10.9"
opencv-python = "4.9.0.80"
termcolor = "2.4.0"
bokeh = "3.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
