name: Build & Publish Executable

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Export dependencies
        run: C:\Users\runneradmin\.local\bin\poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - run: python -m site

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v1.1
        with:
          nuitka-version: main
          script-name: ./drumpy/cli.py
          standalone: true
          onefile: false
          include-plugin-directory: "C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages\\pygame_gui\\data"
          include-data-dir: ./resources=./resources
          include-data-files: |
            C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/pygame_gui/data/*.*=pygame_gui/data/
            C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/pygame_gui/data/translations/*=pygame_gui/data/translations/
          enable-console: true
          enable-plugins: no-qt
          company-name: Mouwrice
          product-name: DrumPy
          product-version: 0.1.0

      - name: Zip
        uses: vimtor/action-zip@v1.2
        with:
          files: build/cli.dist
          dest: DrumPy.zip

      - name: Upload to latest release
        run: gh release upload ${{github.event.release.tag_name}} DrumPy.zip
        env:
          GH_TOKEN: ${{ github.token}}
