name: Build & Publish Binaries

on:
  push:
    branches:
      - main


jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - run: python -m site

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v1.1
        with:
          nuitka-version: main
          script-name: ./drumpy/cli.py
          standalone: true
          include-plugin-directory: "C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages\\pygame_gui\\data"
          include-data-dir: ./DrumSamples=./DrumSamples
          include-data-files: |
            ./*.task=./
            C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/pygame_gui/data/*.*=pygame_gui/data/
            C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/pygame_gui/data/translations/*=pygame_gui/data/translations/
          enable-console: true
          enable-plugins: no-qt
          company-name: Mouwrice
          product-name: DrumPy
          product-version: 0.1.0

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
