name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4.1.4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Export dependencies
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - uses: chartboost/ruff-action@v1
        name: Ruff Lint

      - uses: chartboost/ruff-action@v1
        name: Ruff Format Check
        with:
          args: 'format --check'
