on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: chartboost/ruff-action@v1
        name: Ruff Lint

      - uses: chartboost/ruff-action@v1
        name: Ruff Format Check
        with:
          args: 'format --check'
